/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class AdminSignUp extends javax.swing.JFrame {

    /**
     * Creates new form AdminSignUp
     */
    public AdminSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StrAdp = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Admin Sign Up");
        setMinimumSize(new java.awt.Dimension(565, 470));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel1.setText("Enter ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 160, 149, 37);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel2.setText("Enter Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 210, 149, 30);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel3.setText("Enter Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 125, 28);

        name.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        getContentPane().add(name);
        name.setBounds(250, 120, 296, 34);

        ID.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        getContentPane().add(ID);
        ID.setBounds(250, 160, 296, 37);

        Password.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        getContentPane().add(Password);
        Password.setBounds(250, 210, 297, 37);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jButton1.setText("SignUp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 400, 99, 37);

        jButton2.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 350, 75, 37);

        jButton3.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 350, 71, 37);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel4.setText("New Admin Sign Up");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(113, 0, 305, 41);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel6.setText("Admin Password :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 250, 180, 40);

        StrAdp.setForeground(new java.awt.Color(255, 255, 255));
        StrAdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrAdpActionPerformed(evt);
            }
        });
        getContentPane().add(StrAdp);
        StrAdp.setBounds(250, 260, 300, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminnew.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-6, 0, 570, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nm = name.getText();
        String id = ID.getText();
        String pass = Password.getText();
        String adpass = StrAdp.getText();
        if(nm.isEmpty()||id.isEmpty()||pass.isEmpty()||adpass.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please fill all the Entries","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(adpass.equals("1234"))
            {
                try{
                    Class.forName("com.mysql.jdbc.Driver");

                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schooladmin",
                                                                 "root",
                                                                 "mysql");

                    Statement stmt = con.createStatement();

                    String query = "insert into AdminLogin values('" +nm+ "','" +id+ "','" +pass+ "')";

                    if (nm.matches("")||id.matches("")||pass.matches(""))
                    {
                        JOptionPane.showMessageDialog(this, "Please fill all the Entries");
                    }

                    else
                    {   stmt.executeUpdate(query);
                        JOptionPane.showMessageDialog(this,"You are now an Admin");
                        new AdminHomePage().setVisible(true);
                        this.dispose();
                    }
                }catch(ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this, "ID already Exists");}
            }
            else 
                JOptionPane.showMessageDialog(this, "Incorrect Admin Password","Error",JOptionPane.ERROR_MESSAGE);
            name.setText("");
            ID.setText("");
            Password.setText("");
            StrAdp.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(this,"Thank You For Using" + "\n"
                                        + "Created By :-" + "\n"
                                        + "Sanidhya Teni" + "\n"
                                        + "Mahasvin Raj Mittal" + "\n"
                                        + "Aatmik Jain");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void StrAdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrAdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrAdpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField StrAdp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
